dist:
  module: github.com/open-telemetry/opentelemetry-collector-contrib/cmd/otelcontribcol
  name: otelcontribcol-custom
  description: Local OpenTelemetry Collector Contrib binary, testing only.
  version: 0.102.0-custom
  otelcol_version: 0.102.0

extensions:
  - gomod: go.opentelemetry.io/collector/extension/zpagesextension v0.101.1-0.20240529223953-eaab76e46d38
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/extension/healthcheckextension v0.101.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/extension/healthcheckv2extension v0.101.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/extension/pprofextension v0.101.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/extension/storage/filestorage v0.101.0

receivers:
  - gomod: go.opentelemetry.io/collector/receiver/otlpreceiver v0.101.1-0.20240529223953-eaab76e46d38
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/prometheusreceiver v0.101.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/filelogreceiver v0.101.0

connectors:
  # NOTE: Custom connector!
  - gomod: github.com/hwrdtm/filteringrouter

processors:
  - gomod: go.opentelemetry.io/collector/processor/batchprocessor v0.101.1-0.20240529223953-eaab76e46d38

exporters:
  # NOTE: Prior to v0.86.0 use the `loggingexporter` instead of `debugexporter`.
  - gomod: go.opentelemetry.io/collector/exporter/debugexporter v0.101.1-0.20240529223953-eaab76e46d38
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/exporter/fileexporter v0.101.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/exporter/googlecloudexporter v0.101.0

replaces:
  - github.com/open-telemetry/opentelemetry-collector-contrib/extension/healthcheckextension => ../../extension/healthcheckextension
  - github.com/open-telemetry/opentelemetry-collector-contrib/extension/healthcheckv2extension => ../../extension/healthcheckv2extension
  - github.com/open-telemetry/opentelemetry-collector-contrib/extension/pprofextension => ../../extension/pprofextension
  - github.com/open-telemetry/opentelemetry-collector-contrib/extension/storage/filestorage => ../../extension/storage/filestorage
  - github.com/open-telemetry/opentelemetry-collector-contrib/receiver/prometheusreceiver => ../../receiver/prometheusreceiver
  - github.com/open-telemetry/opentelemetry-collector-contrib/receiver/filelogreceiver => ../../receiver/filelogreceiver
  - github.com/open-telemetry/opentelemetry-collector-contrib/exporter/fileexporter => ../../exporter/fileexporter
  - github.com/open-telemetry/opentelemetry-collector-contrib/exporter/googlecloudexporter => ../../exporter/googlecloudexporter
  - github.com/hwrdtm/filteringrouter => ../../../../hwrdtm/rust-examples/simple-observability-pipeline/filteringrouter