extensions:
  health_check:
  pprof:
    endpoint: 0.0.0.0:1777
  zpages:
    endpoint: 0.0.0.0:55679
  file_storage/filelogreceiver_logs:
    directory: /var/lib/otelcol/file_storage/filelogreceiver_logs
  file_storage/filelogreceiver_metrics:
    directory: /var/lib/otelcol/file_storage/filelogreceiver_metrics
  file_storage/filelogreceiver_traces:
    directory: /var/lib/otelcol/file_storage/filelogreceiver_traces

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

  # Collect own metrics
  prometheus:
    config:
      scrape_configs:
      - job_name: 'otel-collector'
        scrape_interval: 10s
        static_configs:
        - targets: ['0.0.0.0:8888']

  filelog/logs:
    include: [/otel_logs.log]
    storage: file_storage/filelogreceiver_logs
  filelog/metrics:
    include: [/otel_metrics.log]
    storage: file_storage/filelogreceiver_metrics
  filelog/traces:
    include: [/otel_traces.log]
    storage: file_storage/filelogreceiver_traces

connectors:
  filteringrouter/logs:
  filteringrouter/metrics:
  filteringrouter/traces:

processors:
  batch:

exporters:
  file:
    path: /tmp/otel-collector-file-export.json
  googlecloud:
    log:
      default_log_name: opentelemetry.io/collector-exported-log
  debug:
    verbosity: detailed

service:
  pipelines:
    logs/for_logs:
      receivers: [filelog/logs]
      exporters: [filteringrouter/logs]
    logs:
      receivers: [filteringrouter/logs]
      exporters: [debug, googlecloud]

    logs/for_metrics:
      receivers: [filelog/metrics]
      exporters: [filteringrouter/metrics]
    metrics:
      receivers: [filteringrouter/metrics]
      exporters: [debug, googlecloud]

    logs/for_traces:
      receivers: [filelog/traces]
      exporters: [filteringrouter/traces]
    traces:
      receivers: [filteringrouter/traces]
      exporters: [debug, googlecloud]

  extensions: [health_check, pprof, zpages, file_storage/filelogreceiver_logs, file_storage/filelogreceiver_metrics, file_storage/filelogreceiver_traces]

