[workspace]
members = [
    "arc-references",
    "cargo-features",
    "closures",
    "commands",
    "fs",
    "locks",
    "long-running-task-checker",
    "mock-structs",
    "retry",
    "rocket",
    "serde",
]