[package]
name = "retry-basic"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "*"
async-trait = "0.1.53"
tokio = { version = "1.25.0", features = ["full"] }