[package]
name = "fn-mut-arg"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "*"
futures = "0.3.17"
tokio = { version = "1.23.0", features = ["full", "rt-multi-thread"] }